version: "3.9"
services:
  mySql_java-club:
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: java-club
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - databases:/var/lib/mySql_java-club
    ports:
      - '3306:3306'

  mySql_coffee-jug:
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: coffee-jug
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - databases:/var/lib/mySql_coffee-jug
    ports:
      - '3307:3306'

volumes:
  databases: